version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tbpro
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./db:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: tobapro
    restart: always
    ports:
      - 8080:80
    environment:
      VIRTUAL_HOST: tobapro.local
      VIRTUAL_PORT: 80
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: tbpro
      WORDPRESS_TABLE_PREFIX: tbp_
    volumes:
      - ./wordpress:/var/www/html

volumes:
  db:
  wordpress:

networks:
  default:
    external:
      name: nginx-proxy