version: '3.1'

services:

  wordpress:
    image: wordpress:latest
    container_name: tobapro
    restart: always
    ports:
      - 8080:80
    environment:
      VIRTUAL_HOST: tobapro.local
      VIRTUAL_PORT: 80
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: tbpro
      WORDPRESS_TABLE_PREFIX: tbp_
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - mysql-net
      - nginx-proxy

volumes:
  wordpress:

networks:
  mysql-net:
    external: true
  nginx-proxy:
    external: true